### PR TITLE
update: add --search

### PR DESCRIPTION
**Pull request by du5**
#726 #717 

```bash

python speedtest.py --search="United States"
# python speedtest.py --search "United States"
# set server by search result
python speedtest.py --search="United States" --server 18531
# test command
curl -s https://raw.githubusercontent.com/du5/speedtest-cli/7b3309c/speedtest.py \
| python - --search="United States"
```

```bash
pip install git+https://github.com/du5/speedtest-cli.git
speedtest --search="Hong Kong"
speedtest --search="Hong Kong" --server=13538 --share
```

### CODE REVIEW

**Comment by pepa65** [comment]
Great addition/improvement, the `--search` option!

**Comment by deliciouslytyped** [comment]
@sivel Could you merge / is there a reason this hasn't been merged?

It would also be helpful to be able to manually specify a target, because --server ID fails if the server isn't returned by the limited list given by the php page.

This would also provide a workaround in the interim for the people who find the current --server behaviour too limited.

**Comment by deliciouslytyped** [comment]
Nitpick: --list still lists the usual list instead of the search results.

**Comment by du5** [comment]
@deliciouslytyped haha, Maybe he forgot his GitHub password

**Comment by huyz** [comment]
Why was this PR closed without comment? Was it @du5's [joke](https://github.com/sivel/speedtest-cli/pull/732#issuecomment-698951224) that offended @sivel ?

**Comment by pepa65** [comment]
It would be good to know the reason, for @du5 and potential future contributors.

**Comment by pkishino** [comment]
Yeah, just closing and limiting conversation like in #758  is not cool and in foss spirit.. seriously considering a takeover fork so that people can actually contribute and not be limited by some dev that abandons a project and refuses to look at improvements

**Pull request closed without merging**
