### PR TITLE
[OUTPUT STYLE] Download and Upload

### PR DESCRIPTION
**Pull request by ReXulEc**
### Hi @sivel 👋,

I changed the style of output.

> Before:
> 5ncRPSBXk
> 
> After:
> 5ncRyQ3W4

The old output looked weird and it was very complicated.
To me, this new output looks cute and simple.
That's why I decided to renew it, I hope you like it.

Best regards,
Mert Doğu.

### CODE REVIEW

**Comment by ValZapod** [comment]
BTW do you know how to test both upload and download simultaneously? After all gigabite ethernet is 2 gagbite that way.

**Comment by sivel** [comment]
Even though there are machine parsable outputs, there are people out there using and parsing the existing output.

**Comment by anoppe** [comment]
@ReXulEc i.e. your change is breaking existing 'funtionality'.
You could, however, introduce a cli-option which enables a different output format. just like the `--json` and `--csv` options.

**Comment by ReXulEc** [comment]
> @ReXulEc i.e. your change is breaking existing 'funtionality'.
> You could, however, introduce a cli-option which enables a different output format. just like the `--json` and `--csv` options.

Oh, that makes a lot of sense.

**Pull request closed without merging**
