### PR TITLE
Issue on --list

### PR DESCRIPTION
**Pull request by killmasta93**
Issue on the list command

```
root@prometheus:~# speedtest-cli --list
Retrieving speedtest.net configuration...
Traceback (most recent call last):
  File "/usr/bin/speedtest-cli", line 2000, in <module>
    main()
  File "/usr/bin/speedtest-cli", line 1986, in main
    shell()
  File "/usr/bin/speedtest-cli", line 1875, in shell
    secure=args.secure
  File "/usr/bin/speedtest-cli", line 1091, in __init__
    self.get_config()
  File "/usr/bin/speedtest-cli", line 1174, in get_config
    map(int, server_config['ignoreids'].split(','))
ValueError: invalid literal for int() with base 10: '
```

### CODE REVIEW

**Comment by thevickypedia** [comment]
Does your PR have anything to do with the actual error or has it solved the issue? I ran into the same problem quite recently and I fixed it passing an empty list if `sever_config['ignoreids']` is `None`

**Comment by jdubz666** [comment]
Receiving this error as well. 
How can I resolve this? 
Thanks

**Comment by jwigley** [comment]
Looks like it's fixed on `master` under https://github.com/sivel/speedtest-cli/commit/cadc68b5aef20f28648072cf07a8f155639b81dd

**Comment by killmasta93** [comment]
> Looks like it's fixed on `master` under [cadc68b](https://github.com/sivel/speedtest-cli/commit/cadc68b5aef20f28648072cf07a8f155639b81dd)

Correct updated and got fixed

**Pull request closed without merging**
