### PR TITLE
Added CSV mode 

### PR DESCRIPTION
**Pull request by gonzalo**
I'm happy to make this sugestion as my first GitHub contribution to a project :-).
I've added a --csv *filename* mode that write speedtest results to that filename.

    speedtest-cli --csv bandwith_report.csv

If the file doesn't extists it generates a new one with a header. If it cannot write launches an error. This is a sample result:

    Test server;Date/Time;Latency;Dowload Speed (Kb/s);Upload Speed (Kb/s)
    Grupo TVHoradada (Pilar De La Horadada) [87.32 km];2015-07-06T11:28:32.013159;64.8;59847;25499
    Grupo TVHoradada (Pilar De La Horadada) [87.32 km];2015-07-06T11:29:30.652184;62.22;59636;25775
    TVAlmansa S.L. (Almansa) [50.87 km];2015-07-06T11:32:33.344205;85.19;60257;24798
    TVAlmansa S.L. (Almansa) [50.87 km];2015-07-06T11:33:29.556000;62.26;58992;25111
    ...

You can install a cron jon to execute the test each hour for example and store results for future analysis or graphic.

    $crontab -e
    0 */1 * * * /home/myuser/speedtest-cli --csv bandwith_report.csv >> /dev/null

Edited:
Standar output is been redirected to /dev/null in crontab. It could be interesting to add a --silent mode to use in combination with --csv

### CODE REVIEW

**Comment by gonzalo** [comment]
Combining this script with a web server and dygraphs js library you can get a nice upload/download/latency grapht ;-) 
descarga

**Comment by FatBoyNotSoSlim** [comment]
Hey @gonzalo what was your code for the dygraphs page?

**Comment by gonzalo** [comment]
Here you have it in a repository https://github.com/gonzalo/html-bandwidth-report

**Comment by gonzalo** [comment]
Hi @sivel I see that this branch is marked as "needs-revision". Does it need your revision? my revision? Can I make any contribution? I'll be pleased to collaborate because I'm currently using my branch in some installations to test ISP stability.

**Comment by sivel** [comment]
This PR contains merge conflicts that would need to be resolved.

**Comment by CelsoSantos** [comment]
I really like this functionality instead of running scripts to capture the output. Can I do anything to help this feature get pushed into the "default" app? If not, is there any expected date for release?

**Comment by gonzalo** [comment]
Thanks for your support Celso, I would also like to have this features pushed into master branch. I've been using it to check my ISP connnection. Here you have the sample.
captura de pantalla 2015-11-24 a las 17 32 37

**Comment by C-Duv** [comment]
Good idead, a one-line output format (like CSV) is useful (for monitoring systems).
I think allowing printing CSV directly to STDOUT (instead of a file) could be useful too (can be piped, etc.):
`speedtest-cli --csv -`

**Comment by cjeanneret** [comment]
Hello,

Would be great if the merge conflict could be solved and this PR merged — a CSV (or json, or any other parsable output) is a plus when we want to automate checks and get graphes.

Cheers,

C.

**Comment by sivel** [comment]
Regardless of the merge conflict this PR will not be accepted.  The next release already has machine parseable outputs.

See https://github.com/sivel/speedtest-cli/pull/212

**Pull request closed without merging**
