### PR TITLE
Add support for --share in --csv and --csv-header

### PR DESCRIPTION
**Pull request by kingy444**
As the header says - adding support for share URL in csv output format

### CODE REVIEW

**Comment by kingy444** [comment]
Not sure why travis is failing the build - this is a direct merge from master with some pretty straight forward duplication of functions and variable checking on the speedtest.py file only. Anything you can help with?

**Comment by kingy444** [comment]
it actually looks like the other python builds are failing due to travis itself having issues - see here https://github.com/travis-ci/travis-ci/issues/8363

**Comment by sivel** [comment]
I'm not a fan of this implementation. Should I decide to include this functionality, I'll add it in a more appropriate way.

**Comment by kingy444** [comment]
mi happy to make the change to the functions directly as that's how i would prefer it, just didn't want to mess with your base function code too much. is that what you meant by 'more appropriate way'?

**Pull request closed without merging**
