### PR TITLE
Changed to uppercase B for Bytes

### PR DESCRIPTION
**Pull request by johnybradshaw**
This makes it clearer, and is the standard way of representing the difference between bit and Byte.

### CODE REVIEW

**Comment by kdopen** [comment]
> This makes it clearer, and is the standard way of representing the difference between bit and Byte.

But only in abbreviations such as  kb vs kB or Mb vs MB. But when using the whole word (bit, byte) one sticks with a non-capitalized form unless the unit is a proper name (e.g. Ohm, Volt, Ampere vs miles, inches, bits, or bytes). The only times you would want "Byte" instead of "byte" are

* As the first world of a sentence
* As part of a Title Case sentence

If you are trying to catch those cases, then you also need to change 'bit' to 'Bit' in the same line.

If, instead, you are trying to correct the "Mbit/s" and "Mbyte/s" that are displayed, a more accurate change would be to replace "byte" and "bit" with "B" and "b" respectively - producing the technically correct (but less easy for many to remember) "MB/s" and "Mb/s".

BTW I did check the code, and "Mb" or "MB" are correct for this implementation, not "Mib" or "MiB"

**Review by kokizzu — APPROVED** [review]

**Comment by ZaquL** [comment]
This is wrong, byte is a word, it should be from little letter. School level grammar.

**Comment by jschwender** [comment]
If we talk about a number followed by a prefix and a unit, school grammar is unlikely normative. The most recent standard is IEC 80000-13:2008, and this is the one that is referred by major standardization comittees (BIMP, NIST, IEC).

**Comment by ZaquL** [comment]
Just look into https://en.wikipedia.org/wiki/Byte it is all small letters.

вс, 29 мая 2022 г., 21:07 jschwender ***@***.***>:

**Comment by Forza-tng** [comment]
IMHO, it would be best to use the standard IEC units based on binary instead decimal base, since we always have defined internet speeds with a binary base (1024 bits = 1 kilobit)

With decimal base we have 1000 bytes = 1kB = 8000 bits = 8kbit.
With binary base we have 1024 bytes = 1KiB = 8192 bits = 8 Kibit

Speeds could then be noted as 8192 Kibit/s, 1024 KiB/s, 8 Mibit/s or 1 MiB/s.

https://en.m.wikipedia.org/wiki/Byte#Multiple-byte_units

**Pull request closed without merging**
